name: habit_cli
description: A terminal habit tracker with GitHub-style heatmaps.
version: 1.0.0
repository: https://github.com/Bogghi/habit-cli

environment:
  sdk: ^3.11.3

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  nocterm: ^0.4.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
